# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTk4ZDUzNmM5YzFlNzZmMDIxNzcwNWIxZGU2OTBiYjBkNjUwODY2ZWZjYTcwNDE3OWE3ZDZkMGI1YjcyZmMzMGQ3NjI1NGZjZDBkNGM2MjY1NTBmYTcyNjBmOWMzNzE2OTZmOTk4OTNhMTg4MWNhYzY0ZGM0ZDdmZWRlZDZkMDI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
